---
- hosts: all
  become: yes
  tasks: 
         - name: updating apt cache
           apt: update_cache=true
         
         - name: install required packages
           apt: pkg={{item}} state=present
           with_items:
                - openjdk-8-jre
                - apache2
                - tomcat8
                - mongodb
                
         - name: retrieve EasyRentals package from AWS-S3
           get_url: 
                url: https://s3.amazonaws.com/shiva-project-omega/Application-0.0.1-SNAPSHOT.war 
                dest: /home/shivakumar_chinnam

         - name: move the package to required location
           file: 
                path: /var/lib/tomcat8/webapps/ROOT 
                state: absent

         - name: move war to webapps folder
           file: 
                src: Application-0.0.1-SNAPSHOT.war 
                dest: /var/lib/tomcat8/webapps
           #- name: run mongodb service 
           #service: name: mongod status: started
         - name: run the tomcat server
           service: 
                name: tomcat8 
                state: started

         - name: run the EasyRentals application
           shell: "java -jar /var/lib/tomcat8/webapps/Application-0.0.1-SNAPSHOT.war"
...
